Домашняя работа 13
Barsec13/Playlist-Maker pull request #6
Opened 2023-03-18 15:43 UTC by Barsec13

Создан экран аудиоплеер

2023-03-19 11:18 UTC, NoDopezzz requested changes

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/MediaActivity.kt
> +        val roundingRadius = this.resources.getDimensionPixelSize(R.dimen.roundingRadiusPlayer)
👍 Отличная идея хранить радиус скругления в ресурсах

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/MediaActivity.kt
> +        val jsonTrack = sharedPrefDataTrack.getString(DATA_TRACK, null)
👍 Интересная идея использовать `SharedPreferences` для передачи сохранения трека.

⏫ Я бы посоветовал воспользоваться другим способом передачи аргументов на экран `MediaActivity` через `extras` у `Intent`.  Важно помнить, что через `extras` можно передать только сериализуемые объекты.
Можешь почитать хорошую статью про передачу данных между `Activity` или вернуться же к 8 спринту для повторения материала

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/MediaActivity.kt
> +        trackTime.text = SimpleDateFormat("mm:ss", Locale.getDefault()).format(track.trackTimeMillis.toInt())
⏫ Метод форматирования длительности трека используется в нескольких местах в приложении. Обычно, чтобы упростить переиспользование такого кода создается специальный `object TimeUtils `, который и будет хранить в себе метод `formatTrackDuraction(time: Long)`

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/java/com/practicum/playlistmaker/SearchActivity.kt
> +            //Открыть плеер с данными трека
⏫  Нажатие на трек из истории поиска и из найденных результатов должно обрабатываться одинаково:
- обновляем историю в `SharedPreference`
- обновляем локальный список треков - `historyTracks`
- Вызываем обновление состояния у `tracksHistoryAdapter`
- Открываем `MediaActivity` с передачей трека

Всю эту логику мы можем объединить в один метод. Таким образом мы избежим лишнего повторения кода.

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/res/layout/activity_media.xml
> +    android:weightSum="100">
⏫ Так как в нашей разметке `weight child`'ов не устанавливается, то и в параметр `weightSum` нам не понадобится.

Стоит помнить об одном хорошем принципе [YAGNI](https://ru.wikipedia.org/wiki/YAGNI) - You aren't gonna need it.

2023-03-19 11:18 UTC, kirillNay commented on app/src/main/res/layout/activity_media.xml
> +        android:background="?attr/colorSecondary"
⏫  `android:background="?attr/colorSecondary"` уже определена у родительской `ViewGroup`, а значит распространяется и на все `child`'ы.

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/layout/activity_media.xml
> +        android:layout_marginBottom="@dimen/margin_media"
⚠️ Отступ до обложки трека составляет `24dp`. На верстке же отступ равен `8dp` (bottom у изображения) + `8dp` (top у названия) = `16dp`

<img width="453" alt="image" src="https://user-images.githubusercontent.com/56832972/226171135-ec920217-6c87-4fef-a5da-71de7b5be7a9.png">

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/layout/activity_media.xml
> +        android:textSize="@dimen/text_size_20"
⚠️ Судя макетам размер шрифта составляет `22sp`

<img width="991" alt="image" src="https://user-images.githubusercontent.com/56832972/226171301-4b144671-27f5-4d5f-b4d2-ad27b4bc530c.png">

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/layout/activity_media.xml
> +        app:layout_constraintHorizontal_chainStyle="spread_inside"
👍 Отличная идея - соединить кнопки в одну `chain`

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/layout/activity_media.xml
> +        android:layout_marginTop="@dimen/margin_media"
⚠️ Отступ между именем артиста и кнопкой проигрования составляет почти `40dp`. В данном случае установлено лишь `8dp`.
Вообще лучше ориентироваться на маленькие кнопки, т.к. отступы от них до имени артиста составляют целое число - `54dp`

<img width="426" alt="image" src="https://user-images.githubusercontent.com/56832972/226171530-b19b5dbf-e45c-4462-9cf0-53e76f3b51e7.png">

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +    <style name="data_name_track">
⏫ Имена стилей обычно называют в `CamelCase` с заглавной буквой

2023-03-19 11:18 UTC, NoDopezzz commented on app/src/main/res/values/styles.xml
> +        <item name="layout_constraintStart_toStartOf">@id/left_guideline</item>
⏫ Советую в стили выносить только стилистические аттрибуты - цвет, шрифт, размер и т.п. А атрибуты расположения, например `layout_constraintStart_toStartOf`, оставлять в файле разметки. Так, у нас не будет проблем при переиспользовании этого же стиля на других экранах.

2023-03-19 21:19 UTC, NoDopezzz approved these changes

2023-03-23 15:40 UTC, Barsec13 commented
Добавлен экран плеера

2023-03-23 15:40 UTC, merged